##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: clean-arquitecture-sucursal
  devtools:
    add-properties: false
  profiles:
    include:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
